<definitions xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://services.reliance.com/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://services.reliance.com/" name="ldapauthn">
    <types>
    <xsd:schema>
    <xsd:import namespace="http://services.reliance.com/" schemaLocation="http://stoid.jio.com:7010/ssloidws/ldapauthn?xsd=1"/>
    </xsd:schema>
    </types>
    <message name="ldapConenction">
    <part name="parameters" element="tns:ldapConenction"/>
    </message>
    <message name="ldapConenctionResponse">
    <part name="parameters" element="tns:ldapConenctionResponse"/>
    </message>
    <portType name="LDAPAuthentication">
    <operation name="ldapConenction">
    <input wsam:Action="http://services.reliance.com/LDAPAuthentication/ldapConenctionRequest" message="tns:ldapConenction"/>
    <output wsam:Action="http://services.reliance.com/LDAPAuthentication/ldapConenctionResponse" message="tns:ldapConenctionResponse"/>
    </operation>
    </portType>
    <binding name="ldapauthnBinding" type="tns:LDAPAuthentication">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
    <operation name="ldapConenction">
    <soap:operation soapAction=""/>
    <input>
    <soap:body use="literal"/>
    </input>
    <output>
    <soap:body use="literal"/>
    </output>
    </operation>
    </binding>
    <service name="ldapauthn">
    <port name="ldapauthn" binding="tns:ldapauthnBinding">
    <soap:address location="http://stoid.jio.com:7010/ssloidws/ldapauthn"/>
    </port>
    </service>
    </definitions>
    