
package com.reliance.services;

import java.util.List;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LDAPAuthentication", targetNamespace = "http://services.reliance.com/")
@XmlSeeAlso({
                ObjectFactory.class
})
public interface LDAPAuthentication {

        /**
         * 
         * @param arg1
         * @param arg0
         * @return
         *         returns java.util.List<java.lang.Object>
         */
        @WebMethod
        @WebResult(targetNamespace = "")
        @RequestWrapper(localName = "ldapConenction", targetNamespace = "http://services.reliance.com/", className = "com.reliance.services.LdapConenction")
        @ResponseWrapper(localName = "ldapConenctionResponse", targetNamespace = "http://services.reliance.com/", className = "com.reliance.services.LdapConenctionResponse")
        @Action(input = "http://services.reliance.com/LDAPAuthentication/ldapConenctionRequest", output = "http://services.reliance.com/LDAPAuthentication/ldapConenctionResponse")
        public List<Object> ldapConenction(
                        @WebParam(name = "arg0", targetNamespace = "") String arg0,
                        @WebParam(name = "arg1", targetNamespace = "") String arg1);

}
