
package com.reliance.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ldapauthn", targetNamespace = "http://services.reliance.com/", wsdlLocation = "http://stoid.jio.com:7010/ssloidws/ldapauthn?wsdl")
public class Ldapauthn
    extends Service
{

    private final static URL LDAPAUTHN_WSDL_LOCATION;
    private final static WebServiceException LDAPAUTHN_EXCEPTION;
    private final static QName LDAPAUTHN_QNAME = new QName("http://services.reliance.com/", "ldapauthn");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://stoid.jio.com:7010/ssloidws/ldapauthn?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LDAPAUTHN_WSDL_LOCATION = url;
        LDAPAUTHN_EXCEPTION = e;
    }

    public Ldapauthn() {
        super(__getWsdlLocation(), LDAPAUTHN_QNAME);
    }

    public Ldapauthn(WebServiceFeature... features) {
        super(__getWsdlLocation(), LDAPAUTHN_QNAME, features);
    }

    public Ldapauthn(URL wsdlLocation) {
        super(wsdlLocation, LDAPAUTHN_QNAME);
    }

    public Ldapauthn(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LDAPAUTHN_QNAME, features);
    }

    public Ldapauthn(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Ldapauthn(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LDAPAuthentication
     */
    @WebEndpoint(name = "ldapauthn")
    public LDAPAuthentication getLdapauthn() {
        return super.getPort(new QName("http://services.reliance.com/", "ldapauthn"), LDAPAuthentication.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LDAPAuthentication
     */
    @WebEndpoint(name = "ldapauthn")
    public LDAPAuthentication getLdapauthn(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.reliance.com/", "ldapauthn"), LDAPAuthentication.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LDAPAUTHN_EXCEPTION!= null) {
            throw LDAPAUTHN_EXCEPTION;
        }
        return LDAPAUTHN_WSDL_LOCATION;
    }

}
